server:
  port: 8761

eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 3000
  instance:
    hostname: 47.99.242.122
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
    prefer-ip-address: true
    #instance-id : ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}:@project.version@
    status-page-url: http://${eureka.instance.hostname}:${server.port}/swagger-ui.html
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/